project_id = "qsjisndjbjeoqwbairal"

[functions.justwatch-lookup]
verify_jwt = false

[functions.plex-import]
verify_jwt = false

[functions.tmdb-search]
verify_jwt = false

[functions.real-debrid]
verify_jwt = false